name: Build Docker image

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd tvb_build/docker && docker build . --file Dockerfile --tag tvb
